[Node.P2P]
bootnodes = [
    "/ip4/40.112.209.145/tcp/80/p2p/16Uiu2HAkxWKQfZfGxh68TP5WLQucEKfuNwNHf4cNSrfx9s6Uwbui",
    "/ip4/127.0.0.1/tcp/3001/p2p/16Uiu2HAmLddH8TFAyq7Bx9qD7BWXTDgLQFTMdP8ovBUkrkHN4dkv"
]
